### ISSUE TITLE
Width of Trees (from Yahoo group)

### ISSUE THREAD

**Issue by GuillaumeBrochu** [geneweb/geneweb_tmp#60]
(published on the Yahoo group on 28-08-2016, https://groups.yahoo.com/neo/groups/geneweb/conversations/messages/6736)

Hi,

This message is addressed to the coders and maintainers of GeneWeb.  

I love the system and have been using for many years both on Geneanet and on my own "Vaucher" databases housed at U.deMontreal.  I especially like the ANCESTOR and DESCENDANT tree facilities except for one thing... the excessive width of the printed trees.  I ran across this when I added about 200 new Vauchers from Uruguay and Brazil to my database and similarly with my French Canadian family with 12-15 children per generation.

Geneweb uses a simple grid layout scheme which uses one "column" for every LEAF - a couple without children -  (See attached JPG):   (N/2) columns in the BEST case for N people; but often close to N columns.  However simple algorithms exist which give much slimmer yet elegant trees.  Many papers were published on the subject around 1980 .  I published one in "Software Practice and Experience" vol 10, 553-561 (1980) but independently Wetherell published in IEEE Trans of Software engineering (sept 1979) and Reinhold in IEEE Trans Soft Eng (March 1981).

Example:  Assume X has 3 generations of descendants in which there is only one fruitful child per generation, like below.  It is fairly clear that you could print the children of every generation right under the previous one, using only 5 columns for the 16 people.

```  

                    X

                    |

              +--+--+--+--+

             12 13 14 15 16

                    |

              +--+--+--+--+

              6  7  8  9  10

                    |

              +--+--+--+--+       

              1  2  3  4  5
```

However, Geneweb will use the following layout with 12 columns (over twice the size):

```
                    X

                    |

   +--+-------------+---------------+--+

   12 13            14              15 16

                    |

        +--+--------+--------+--+

        6  7        8        9  10

                    |

              +--+--+--+--+       

              1  2  3  4  5
```

If anyone is interested, I will send the pseudo code or copies of the articles.  I repeat, "the algorithm is TRIVIAL"

Jean Vaucher

jgvaucher@...

**Comment by vaucher** [comment]
I include a zipped folder with a complete Java program which produces trees which are much narrower than the ones presently produced by Geneweb. The KEY part of the program is a small "position"; algorithm which determines X,Y positions for each Node. 


The program itself is much larger because it includes INPUT routines to read tree descriptions and HTML OUTPUT routines. The HTML produced is quite primitive compared to Geneweb's but sufficient to show what "POSITION"; can do. 
[Tree_export.zip](https://github.com/geneweb/geneweb/files/465223/Tree_export.zip)

**Comment by ipfix** [comment]
This issue was moved to geneweb/geneweb#414
