### ISSUE TITLE
Chemin complet des images dans les .GED produits par gwb2ged

### ISSUE THREAD

**Issue by GuillaumeBrochu** [geneweb/geneweb_tmp#61]
Suggestion d'amélioration reçue de Gilles Lecomte, par e-mail:

> Aussi je me permets de vous suggérer d'indiquer le chemin des fichiers image dans le gedcom.
> Pour chaque individu (dont on connaît le nom, le prénom et l'occurence), il faudrait tester la présence du fichier dans le répertoire image de la base, et si oui, on rajoute les quelque lignes qui indiquent le chemin de l'image associée.
> 
> Ça permettrait notamment d'utiliser Geneanet Upload afin de télécharger l'intégralité des images au lieu de les télécharger une par une...

Exemple de ligne désirée dans le .GED:

```
2 FILE C:\Genealogie\geneweb\bases\images\mabase\BROCHU-Guillaume.0-1.jpeg 
```

au lieu de ceci:

```
2 FILE BROCHU-Guillaume.0-1.jpeg 
```

Suggestion : ajouter une option de ligne de commande à gwb2ged

**Comment by GuillaumeBrochu** [comment]
Voir aussi : https://github.com/geneweb/geneweb/issues/45

**Comment by ipfix** [comment]
This issue was moved to geneweb/geneweb#413
